### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by doramail** [zinuzoid/XCSoar#20]
Expected behavior
-----------------

Normal installation without error messages

Actual behavior
---------------

Installation failed because :
Message returned is : [INSTALL_FAILED_CONFLICTING_PROVIDER: Scanning Failed.: Can't install because provider name xcsoar (in package com.zinuzoid.xcsoar_jet) is already used by org.xcsoar]

Steps to reproduce the behavior
-------------------------------

Each time I launch the .apk from github.com/zinuzoid/XCSoar last version (v1.10 [25 Apr 2022]) on top of the original XCSoar version 7.22.

Do you have any idea what may have caused this?
-----------------------------------------------

An already installed version of the original XCSoar application. (not the JET version)

Do you have an idea how to solve the issue?
-------------------------------------------

Yes, only the programmer can do it by recompiling the app.

**Comment by doramail** [comment]
XCSoar versions having and not having the problem
-------------------------------------------------

XCSoar (not the JET version) version used when seeing XCSoar 7.23 ?


Expected behavior
-----------------


Normal installation without error messages



Actual behavior
---------------

Installation failed because :
Message returned is : [INSTALL_FAILED_CONFLICTING_PROVIDER: Scanning Failed.: Can't install because provider name xcsoar (in package com.zinuzoid.xcsoar_jet) is already used by org.xcsoar]



Steps to reproduce the behavior
-------------------------------


Each time I launch the .apk from github.com/zinuzoid/XCSoar last version (v1.10 [25 Apr 2022)



Do you have any idea what may have caused this?
-----------------------------------------------


An already installed version of the original XCSoar application. (not the JET version)



Do you have an idea how to solve the issue?
-------------------------------------------


no, only the programmer can do it.

**Comment by zinuzoid** [comment]
I finally fixed this issue on v1.12. Let me know if you still face the issue.

**Comment by doramail** [comment]
Hi, thank you very much, the issue has been effectively fixed, version 1.12 works perfectly.
Best regards
