### ISSUE TITLE
Transparent info boxes.

### ISSUE THREAD

**Issue by XCNav** [zinuzoid/XCSoar#21]
XCSoar version
--------------

7.3 JET

What should XCSoar do differently, what functionality should be added?
----------------------------------------------------------------------

 Make transparency of info boxes a choice and infoboxes a layover of the background map.

What are you trying to do, what is the use case for the suggestion?
-------------------------------------------------------------------

 More modern graphical design as seen in LK8000 or LX devices, more visible mapspace

**Comment by zinuzoid** [comment]
Thanks for the idea but, it's not very straight forward to do in the current codebase.
So probably I would never have time to do it.
