### ISSUE TITLE
FTDI FT232 Dual Support

### ISSUE THREAD

**Issue by XCNav** [zinuzoid/XCSoar#22]
XCSoar versions having and not having the problem
-------------------------------------------------

Expected behavior
-----------------

Actual behavior
---------------

 Whenn connecting two ft232, XCSOAR Jet only recognizes one of the 2

Steps to reproduce the behavior
-------------------------------

 connect 2 ftdi uart connerter via usb

Do you have any idea what may have caused this?
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------

 https://github.com/LK8000/LK8000/commit/d8cdbbde75fe543957e7a2377b473890a35a0875

**Comment by zinuzoid** [comment]
This was fixed in the upstream. This is now included in v1.14.

https://github.com/zinuzoid/XCSoar/commit/76b830e424031185b9ce90c33d0dea1bebca35a1
