### ISSUE TITLE
Android 11 Crash

### ISSUE THREAD

**Issue by XCNav** [zinuzoid/XCSoar#34]
XCSoar versions having and not having the problem
-------------------------------------------------

XCSO Jet 1.2 

System information
------------------

XCNAV Edition Android 11

Steps to reproduce the behavior
-------------------------------

Expected behavior
-----------------

Actual behavior
---------------

XCSOAR Jet crashing on startup

Do you have any idea what may have caused this?
-----------------------------------------------

See attached log

Do you have an idea how to solve the issue?
-------------------------------------------

**Comment by XCNav** [comment]
![xcsoar_XCSoarJET_20240519_1147_ErrVer7.42.log.txt](https://github.com/zinuzoid/XCSoar/files/15377226/xcsoar_XCSoarJET_20240519_1147_ErrVer7.42.log.txt)

**Comment by zinuzoid** [comment]
Hmm, there's not much information in the log file. I would expect to see some error message or stack trace but it's not there.

I think there'll be more information in device adb log, so it would be useful to capture that when the crash happens.

**Comment by zinuzoid** [comment]
Likely fixed via https://github.com/XCSoar/XCSoar/pull/1556

**Comment by XCNav** [comment]
Thanks for info
